export default {
  FETCH_RESTAURANT: "FETCH_RESTAURANT",
  FETCH_HOTEL: "FETCH_HOTEL",

  FETCH_THEPLACE: "FETCH_THEPLACE",

  CLEAR_THE_PLACE: "CLEAR_THE_PLACE",

  FETCH_PLACES_ERROR: "FETCH_PLACES_ERROR"
};
